chore: Update API version and deployment conditions in theme-preview.yml

diff --git a/.github/workflows/theme-preview.yml b/.github/workflows/theme-preview.yml
--- a/.github/workflows/theme-preview.yml
+++ b/.github/workflows/theme-preview.yml
@@ -1,73 +1,91 @@
-name: Shopify Theme Management
+# name: Shopify Theme Management
 
+# on: [push]
+# # on:
+# #   push:
+# #     branches:
+# #       - "*"
+# #   pull_request:
+# #     types: [opened, synchronize, closed]
+
+# jobs:
+#   manage-theme:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repo
+#         uses: actions/checkout@v4.1.7
+
+#       - name: Debug API Authentication
+#         run: |
+#           echo "Testing API connection..."
+#           response=$(curl -sS -o /dev/null -w "%{http_code}" -X GET "https://${{ secrets.SHOP_STORE }}/admin/api/2024-10/shop.json" \
+#             -H "Content-Type: application/json" \
+#             -H "X-Shopify-Access-Token: ${{ secrets.SHOP_PASSWORD }}")
+#           echo "API Response Code: $response"
+#           if [ "$response" = "200" ]; then
+#             echo "API connection successful"
+#           else
+#             echo "API connection failed"
+#             exit 1
+#           fi
+#         env:
+#           SHOP_STORE: ${{ secrets.SHOP_STORE }}
+#           SHOP_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
+
+#       - name: Deploy branch-specific or PR-specific Shopify theme
+#         if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
+#         uses: matthew-petrie/shopify-theme-actions@1.2.2
+#         with:
+#           ACTION: "DEPLOYMENT_PREVIEW"
+#           SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
+#           SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
+#           SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
+#           SHOPIFY_THEME_DIRECTORY: "."
+#           SHOPIFY_ALLOW_LIVE_THEME_DEPLOYMENT: false
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+#       - name: Remove PR-specific Shopify theme
+#         if: github.event_name == 'pull_request' && github.event.action == 'closed'
+#         uses: matthew-petrie/shopify-theme-actions@1.2.2
+#         with:
+#           ACTION: "REMOVE_DEPLOYMENT_PREVIEW_THEME"
+#           SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
+#           SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
+#           SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           SHOPIFY_THEME_DIRECTORY: "."
+
+#       - name: Remove branch-specific Shopify theme
+#         if: github.event_name == 'push' && github.event.deleted
+#         uses: matthew-petrie/shopify-theme-actions@1.2.2
+#         with:
+#           ACTION: "REMOVE_DEPLOYMENT_PREVIEW_THEME"
+#           SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
+#           SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
+#           SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           SHOPIFY_THEME_DIRECTORY: "."
+
+#       - name: Debug Action Output
+#         run: |
+#           echo "GitHub event name: ${{ github.event_name }}"
+#           echo "GitHub event action: ${{ github.event.action }}"
+#           echo "Branch or PR: ${{ github.ref }}"
+
+name: "Deploy Preview"
 on: [push]
-# on:
-#   push:
-#     branches:
-#       - "*"
-#   pull_request:
-#     types: [opened, synchronize, closed]
 
 jobs:
-  manage-theme:
+  deploy:
     runs-on: ubuntu-latest
+    name: "Deployment"
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4.1.7
-
-      - name: Debug API Authentication
-        run: |
-          echo "Testing API connection..."
-          response=$(curl -sS -o /dev/null -w "%{http_code}" -X GET "https://${{ secrets.SHOP_STORE }}/admin/api/2024-10/shop.json" \
-            -H "Content-Type: application/json" \
-            -H "X-Shopify-Access-Token: ${{ secrets.SHOP_PASSWORD }}")
-          echo "API Response Code: $response"
-          if [ "$response" = "200" ]; then
-            echo "API connection successful"
-          else
-            echo "API connection failed"
-            exit 1
-          fi
-        env:
-          SHOP_STORE: ${{ secrets.SHOP_STORE }}
-          SHOP_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
-
-      - name: Deploy branch-specific or PR-specific Shopify theme
-        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
-        uses: matthew-petrie/shopify-theme-actions@1.2.2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+      - name: "Deploy Theme"
+        uses: wyugen/shopify-theme-action@v0.3
         with:
-          ACTION: "DEPLOYMENT_PREVIEW"
-          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
-          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
-          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
-          SHOPIFY_THEME_DIRECTORY: "."
-          SHOPIFY_ALLOW_LIVE_THEME_DEPLOYMENT: false
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Remove PR-specific Shopify theme
-        if: github.event_name == 'pull_request' && github.event.action == 'closed'
-        uses: matthew-petrie/shopify-theme-actions@1.2.2
-        with:
-          ACTION: "REMOVE_DEPLOYMENT_PREVIEW_THEME"
-          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
-          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
-          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SHOPIFY_THEME_DIRECTORY: "."
-
-      - name: Remove branch-specific Shopify theme
-        if: github.event_name == 'push' && github.event.deleted
-        uses: matthew-petrie/shopify-theme-actions@1.2.2
-        with:
-          ACTION: "REMOVE_DEPLOYMENT_PREVIEW_THEME"
-          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
-          SHOPIFY_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
-          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY_THEME }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SHOPIFY_THEME_DIRECTORY: "."
-
-      - name: Debug Action Output
-        run: |
-          echo "GitHub event name: ${{ github.event_name }}"
-          echo "GitHub event action: ${{ github.event.action }}"
-          echo "Branch or PR: ${{ github.ref }}"
+          SHOPIFY_STORE: ${{secrets.SHOP_STORE}}
+          SHOPIFY_APP_PW: ${{secrets.SHOP_PASSWORD}}
+          SHOPIFY_API_KEY: ${{secrets.SHOPIFY_API_KEY_THEME}}
+          github-token: ${{secrets.GITHUB_TOKEN}}
